version: '3.5'

services:
    django_boilerplate: 
        build: .
        # image: app_django_boilerplate
        environment:
            - APP_ENVIRONMENT=staging
            - SECRET_KEY_VALUE=bDf%Ma*y8HX6S2zZVMP37bbWc^zLT#jwDTFMP7hZFZvWczeD5@
            - DEBUG_VALUE=true
            - ALLOWED_HOSTS_VALUE=*
            - DATABASE_NAME_VALUE=django_boilerplate
            - DATABASE_USER_VALUE=postgres-admin
            - DATABASE_PASSWORD_VALUE=j*B&72_#AX_wj8*MgY=j!4u=^b?M*Mwtu@%K
            - DATABASE_HOSTNAME_VALUE=db
            - DATABASE_PORT_VALUE=5432
        restart: unless-stopped
        depends_on:
            - db
        networks:
            - internal_db
            - reverse_proxy

    db:
        image: postgres:11.1
        environment:
            - POSTGRES_USER=postgres-admin
            - POSTGRES_PASSWORD=j*B&72_#AX_wj8*MgY=j!4u=^b?M*Mwtu@%K
            - POSTGRES_DB=django_boilerplate
        volumes:
            - db-data:/var/lib/postgresql/data
        restart: unless-stopped
        networks:
            - internal_db

    reverseproxy:
        image: nginx:1.15-alpine
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        volumes:
            - /app/tools/ssl:/etc/ssl
            - /app/tools/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - django_boilerplate
        networks:
            - reverse_proxy

volumes:
    db-data:

networks:
    internal_db:
    reverse_proxy:
